language: python
python:
  - "3.10"
  - "3.11"

dist: bionic

addons:
  postgresql: "10.10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

install:
  - pip install codecov tox

services:
  - postgresql

before_script:
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 10.10
  - psql -c 'CREATE DATABASE tracking_analyzer_test;' -U postgres

script:
  - tox --

after_success:
  - codecov

env:
  - TOXENV=django40
  - TOXENV=django50
